touch 0-alias
touch 1-hello_you
touch 2-path
touch 3-paths
touch 4-global_variables
touch 5-local_variables
touch 6-create_local_variable
touch 7-create_global_variable
touch 8-true_knowledge
touch 9-divide_and_rule
touch 10-love_exponent_breath
touch 11-binary_to_decimal
touch 12-combinations
touch 13-print_float
touch 14-decimal_to_hexadecimal
