# Setup a simple development environment
#
# Single box with VirtualBox provider and Puppet provisioning.
#

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "concatidev"
  config.vm.network "forwarded_port", guest: 8000, host: 8080, auto_correct: true

  config.vm.provision :puppet do |puppet|
    puppet.options = "--verbose"
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "puppet/modules"
  end
end
